################### 消息系统配置信息 ###############
#msgsys代表以下配置是消息系统相关的配置
msgsys:
  #IP代表消息子系统运行的服务器及访问端口 143.176.22.60:8080/mqxx-service
  IP: 143.176.22.167:8080/mqxx-service
  #使用消息的微服务的组ID，需要标识唯一性。 test_msg_cnki :// TYYW_LCBA_CNKI-SYS_520000
  GROUP_ID: test_msg_cnki
server:
  port: 8080
cnkiconf:
  name: test
  csb:
    url: http://csb-broker.tyyw1.gz.jcy:8086/CSB
    ak: test
    sk: test
    #获取起诉意见书接口
    getQSYJS: GetQSYJS
    #接口版本号
    getQSYJSVersion: 1.0.0
    #接口提交方法
    getQSYJSMethon: post
    #接口获取延时（毫秒）
    getQSYJSWait: 1
    #存放目录
    getQSYJSPath: D:\test\qsyjs\
    #激活类案推送的zip解析接口
    sendFilepathURL: http://127.0.0.1/cich/request/ExecZipAPI.ashx?bmsah={bmsah}&zippath={zippath}
    getQSYJSSystemId: 330000
    getQSYJSToken: test
    otherapis: GetAJAKXX|tyyw_token+systemid$$GetAJAQZYXX|systemid+tyyw_token


logging:
  file: D:\test\log\springboot.log



