################### 高检院正式的 消息系统配置信息 ###############
#msgsys代表以下配置是消息系统相关的配置
msgsys:
  #IP代表消息子系统运行的服务器及访问端口 143.176.22.60:8080/mqxx-service
  IP: 143.3.213.28:8080
  #使用消息的微服务的组ID，需要标识唯一性。 test_msg_cnki :// TYYW_LCBA_CNKI-SYS_520000，新建消费的时候注意，真实的ID是
  #CID_{GROUP_ID}_consumer_common
  GROUP_ID: TYYW_LCBA_CNKI-SYS_100000
server:
  port: 8080
cnkiconf:
  name: test
  csb:
    url: http://csb-broker.a.yun.gj.jcy:8086/CSB
    ak: test
    sk: test
    #获取起诉意见书接口
    getQSYJS: GetQSYJS
    #接口版本号
    getQSYJSVersion: 1.0.0
    #接口提交方法
    getQSYJSMethon: post
    #接口获取延时（毫秒）
    getQSYJSWait: 1
    #存放目录
    getQSYJSPath: D:\test\qsyjs\
    #激活类案推送的zip解析接口
    sendFilepathURL: http://127.0.0.1/cich/request/ExecZipAPI.ashx?bmsah={bmsah}&zippath={zippath}
    getQSYJSSystemId: 330000
    getQSYJSToken: test
    # 获取案由接口参数
    otherapis: GetAJAKXX|tyyw_token+systemid$$GetAJAQZYXX|systemid+tyyw_token
    # 获取文件方式 0:27号接口方式； 1:4、5号接口； 2:先27在4、5号接口
    getFileType: 2
    # 获取卷宗文件：0:所有文件都获取；1:只获取起诉意见书
    getAJJZType: 0
    # 获取案件卷宗全目录
    getAJJZQML: GetAJJZQML
    getAJJZQMLVersion: 1.0.0
    getAJJZQMLMethon: post
    getAJJZQMLSystemId: 330000
    getAJJZQMLToken: test
    # 获取案件卷宗文件
    getAJJZWJ: GetAJJZWJ
    getAJJZWJVersion: 1.0.0
    getAJJZWJMethon: post
    getAJJZWJSystemId: 330000
    getAJJZWJToken: test
    #激活类案推送的文件夹解析接口
    sendFilepathURL1: http://127.0.0.1/cich/request/ExecZipAPI.ashx?bmsah={bmsah}&path={path}

logging:
  file: D:\test\log\springboot.log



